[features]
seeds = false
skip-lint = false
[programs.localnet]
oracle = "3mDomzG84KDcBkoVgekMc8p8LR86nCQeyDAPPjjKKxec"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jdaviderb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
